### ISSUE TITLE
Is it possible to use other applications than VSCode ?

### ISSUE THREAD

**Issue by Narice** [ANLAB-KAIST/KENSv3-Docker#1]
Hello,
I tried to run KENSv3-Docker, and the docker container seems to be running fine, but VSCode "remote - containers" extension doesn't seem to detect any container (not only KENS).
Is it possible to build and test using just the command line ?
As the app folder is mounted onto the container, I guess I could code directly on the different files, but I don't really see how to build and test as the Makefile in app doesn't seem to work directly from the folder. I suppose it only works while being in the container.
I'm not very familiar with docker and I apologize if the answer is quite simple
Thank you for your dedication

**Comment by Pusnow** [comment]
If you specify port number, you can ssh into KENS container.

```bash
./run.sh 12345
ssh root@127.0.0.1 -p 12345
```

This may be right.

**Comment by Narice** [comment]
oh, thank you so much !
